### ISSUE TITLE
Bug in interpolation search

### ISSUE THREAD

**Issue by mbolivar** [MauriceGit/Advanced_Algorithms#1]
There's a bug in the helper function used to implement interpolation search:

https://github.com/MauriceGit/Advanced_Algorithms/blob/master/Searching/interpolation_search.py#L10

Here's a snippet:

```
def search(S, e, l, r, count):
    # second check to avoid possible division by zero later on
    if l > r or S[l] == S[r]:
        return -1, count
```

The if statement as written incorrectly returns (-1, count) when, for example:

S = [1,1]
e = 1
l = 0
r = 1

A quick fix would be:

```
    if e == S[l]:
        return l, count
    elif l > r or S[l] == S[r]:
        return -1, count
```

But that's a bit ugly. There's probably a better way.

**Comment by MauriceGit** [comment]
I didn't really like that check there anyways, I have to admit.
I did not account for it in the beginning.

Would you like to create a pull request? Otherwise I am happy to correct it myself :)

Thanks for pointing it out!

**Comment by MauriceGit** [comment]
Done, thanks!
